### ISSUE TITLE
Quick crashes in Xcode 6 Beta 7

### ISSUE THREAD

**Issue by TomasLinhart** [Quick/Quick#135]
Hello,

running Quick on Xcode 6 Beta 7 is not working. It fails in file World.swift on line 18.

```
var _specs: Dictionary<String, ExampleGroup> = [:]
```

With following stack trace

```
   #0   0x0000000000000000 in 0x00000000 ()
   #1   0x000000011a1b26cf in create_generic_metadata635 ()
   #2   0x000000011a229457 in swift_getGenericMetadata ()
   #3   0x000000011a2295a9 in swift_getGenericMetadata2 ()
   #4   0x000000011a09bda8 in Swift._copyCollectionToNativeArrayBuffer <A :    protocol<Swift._CollectionType, Swift._Sequence_Type>>(A) -> Swift._ContiguousArrayBuffer<A.Generator.Element> ()
   #5   0x000000011a09f174 in Swift.Array.convertFromHeapArray <A>(Swift.Array<A>.Type)(Builtin.RawPointer, owner : Builtin.NativeObject, count : Builtin.Word) -> Swift.Array<A> ()
   #6   0x000000011a3fc964 in Quick.World.init (Quick.World.Type)() -> Quick.World at /Users/user/Projects/MyApp/MyAppTests/Libraries/Quick/Quick/World.swift:18
   #7   0x000000011a3f92e2 in Quick.World.__allocating_init (Quick.World.Type)() -> Quick.World ()
   #8   0x000000011a3f92a1 in globalinit_func0 at /Users/user/Projects/MyApp/MyAppTests/Libraries/Quick/Quick/World.swift:31
   #9   0x000000011a2367f0 in __swift_once_block_invoke ()
   #10  0x000000011081072d in _dispatch_client_callout ()
   #11  0x000000011080185f in dispatch_once_f ()
   #12  0x000000011a2367cd in swift_once ()
   #13  0x000000011a3f9354 in Quick.World._Shared.instance.addressor : Quick.World at /Users/user/Projects/MyApp/MyAppTests/Libraries/Quick/Quick/World.swift:31
   #14  0x000000011a3f9381 in Quick.World.sharedWorld (Quick.World.Type)() -> Quick.World at /Users/user/Projects/MyApp/MyAppTests/Libraries/Quick/Quick/World.swift:34
   #15  0x000000011a3f93c9 in @objc Quick.World.sharedWorld (Quick.World.Type)() -> Quick.World ()
   #16  0x000000011a4009d3 in +[QuickSpec initialize] at /Users/user/Projects/MyApp/MyAppTests/Libraries/Quick/Quick/QuickSpec.m:36
   #17  0x000000011019d2a9 in _class_initialize ()
   #18  0x000000011019d06d in _class_initialize ()
   #19  0x00000001101a4538 in lookUpImpOrForward ()
   #20  0x00000001101b008c in objc_msgSend ()
   #21  0x00000001105591dd in -[__NSSetM member:] ()
   #22  0x00000001104a6318 in -[NSSet containsObject:] ()
   #23  0x000000011a0568dc in +[XCTestCase(RuntimeUtilities) allSubclasses] ()
   #24  0x000000011a04975d in +[XCTestSuite _suiteForBundleCache] ()
   #25  0x000000011a049935 in +[XCTestSuite suiteForBundleCache] ()
   #26  0x000000011a049cc8 in +[XCTestSuite allTests] ()
   #27  0x000000011a05797d in __33+[XCTestProbe specifiedTestSuite]_block_invoke ()
   #28  0x000000011081072d in _dispatch_client_callout ()
   #29  0x000000011080185f in dispatch_once_f ()
   #30  0x000000011a057924 in +[XCTestProbe specifiedTestSuite] ()
   #31  0x000000011a057de2 in __24+[XCTestProbe runTests:]_block_invoke181 ()
   #32  0x000000011a05212d in -[XCTestObservationCenter _observeTestExecutionForBlock:] ()
   #33  0x000000011a057d15 in +[XCTestProbe runTests:] ()
   #34  0x000000010d9b36dc in __NSFireDelayedPerform ()
   #35  0x0000000110488c34 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ ()
   #36  0x00000001104887b2 in __CFRunLoopDoTimer ()
   #37  0x00000001104717be in __CFRunLoopRun ()
   #38  0x0000000110470d83 in CFRunLoopRunSpecific ()
   #39  0x000000011110ff04 in GSEventRunModal ()
   #40  0x000000010dddfe33 in UIApplicationMain ()
   #41  0x000000010b354ec3 in main at /Users/user/Projects/MyApp/main.m:13
   #42  0x0000000110aa05fd in start ()
```

**Comment by rgula4** [comment]
getting code signing is required for product type 'Application' in SDK 'iOS 8.3 error on ios 8.3 for physical device

**Comment by rgula4** [comment]
xcode version 6.3.2
